package main

import "time"

type AutoGenerated struct {
	Version  string `json:"version"`
	Encoding string `json:"encoding"`
	Feed     struct {
		Xmlns           string `json:"xmlns"`
		XmlnsOpenSearch string `json:"xmlns$openSearch"`
		XmlnsGsx        string `json:"xmlns$gsx"`
		ID              struct {
			T string `json:"$t"`
		} `json:"id"`
		Updated struct {
			T time.Time `json:"$t"`
		} `json:"updated"`
		Category []struct {
			Scheme string `json:"scheme"`
			Term   string `json:"term"`
		} `json:"category"`
		Title struct {
			Type string `json:"type"`
			T    string `json:"$t"`
		} `json:"title"`
		Link []struct {
			Rel  string `json:"rel"`
			Type string `json:"type"`
			Href string `json:"href"`
		} `json:"link"`
		Author []struct {
			Name struct {
				T string `json:"$t"`
			} `json:"name"`
			Email struct {
				T string `json:"$t"`
			} `json:"email"`
		} `json:"author"`
		OpenSearchTotalResults struct {
			T string `json:"$t"`
		} `json:"openSearch$totalResults"`
		OpenSearchStartIndex struct {
			T string `json:"$t"`
		} `json:"openSearch$startIndex"`
		Entry []struct {
			ID struct {
				T string `json:"$t"`
			} `json:"id"`
			Updated struct {
				T time.Time `json:"$t"`
			} `json:"updated"`
			Category []struct {
				Scheme string `json:"scheme"`
				Term   string `json:"term"`
			} `json:"category"`
			Title struct {
				Type string `json:"type"`
				T    string `json:"$t"`
			} `json:"title"`
			Content struct {
				Type string `json:"type"`
				T    string `json:"$t"`
			} `json:"content"`
			Link []struct {
				Rel  string `json:"rel"`
				Type string `json:"type"`
				Href string `json:"href"`
			} `json:"link"`
			GsxLine struct {
				T string `json:"$t"`
			} `json:"gsx$line"`
			GsxDirection struct {
				T string `json:"$t"`
			} `json:"gsx$direction"`
			GsxTrain struct {
				T string `json:"$t"`
			} `json:"gsx$train"`
			GsxSched struct {
				T string `json:"$t"`
			} `json:"gsx$sched"`
			GsxAmMarc struct {
				T string `json:"$t"`
			} `json:"gsx$am-marc"`
			GsxMon struct {
				T string `json:"$t"`
			} `json:"gsx$mon"`
			GsxTue struct {
				T string `json:"$t"`
			} `json:"gsx$tue"`
			GsxWed struct {
				T string `json:"$t"`
			} `json:"gsx$wed"`
			GsxThr struct {
				T string `json:"$t"`
			} `json:"gsx$thr"`
			GsxFri struct {
				T string `json:"$t"`
			} `json:"gsx$fri"`
			GsxSat struct {
				T string `json:"$t"`
			} `json:"gsx$sat"`
			GsxSun struct {
				T string `json:"$t"`
			} `json:"gsx$sun"`
			GsxBike struct {
				T string `json:"$t"`
			} `json:"gsx$bike"`
			GsxR struct {
				T string `json:"$t"`
			} `json:"gsx$r"`
			GsxQ struct {
				T string `json:"$t"`
			} `json:"gsx$q"`
			GsxA100Stop struct {
				T string `json:"$t"`
			} `json:"gsx$a100stop"`
			GsxA100Time struct {
				T string `json:"$t"`
			} `json:"gsx$a100time"`
			GsxA110Stop struct {
				T string `json:"$t"`
			} `json:"gsx$a110stop"`
			GsxA110Time struct {
				T string `json:"$t"`
			} `json:"gsx$a110time"`
			GsxA120Stop struct {
				T string `json:"$t"`
			} `json:"gsx$a120-stop"`
			GsxA120R struct {
				T string `json:"$t"`
			} `json:"gsx$a120-r"`
			GsxNt struct {
				T string `json:"$t"`
			} `json:"gsx$nt"`
			GsxA120Time struct {
				T string `json:"$t"`
			} `json:"gsx$a120time"`
			GsxA130Stop struct {
				T string `json:"$t"`
			} `json:"gsx$a130-stop"`
			GsxA130Nt struct {
				T string `json:"$t"`
			} `json:"gsx$a130-nt"`
			GsxA130R struct {
				T string `json:"$t"`
			} `json:"gsx$a130-r"`
			GsxA130Time struct {
				T string `json:"$t"`
			} `json:"gsx$a130time"`
			GsxA140L struct {
				T string `json:"$t"`
			} `json:"gsx$a140-l"`
			GsxA140Stop struct {
				T string `json:"$t"`
			} `json:"gsx$a140-stop"`
			GsxA140Nt struct {
				T string `json:"$t"`
			} `json:"gsx$a140-nt"`
			GsxA140Time struct {
				T string `json:"$t"`
			} `json:"gsx$a140time"`
			GsxA150Stop struct {
				T string `json:"$t"`
			} `json:"gsx$a150-stop"`
			GsxA150L struct {
				T string `json:"$t"`
			} `json:"gsx$a150-l"`
			GsxA150R struct {
				T string `json:"$t"`
			} `json:"gsx$a150-r"`
			GsxA150Time struct {
				T string `json:"$t"`
			} `json:"gsx$a150time"`
			GsxA160L struct {
				T string `json:"$t"`
			} `json:"gsx$a160-l"`
			GsxA160R struct {
				T string `json:"$t"`
			} `json:"gsx$a160-r"`
			GsxA160Stop struct {
				T string `json:"$t"`
			} `json:"gsx$a160-stop"`
			GsxA160Time struct {
				T string `json:"$t"`
			} `json:"gsx$a160time"`
			GsxA170L struct {
				T string `json:"$t"`
			} `json:"gsx$a170-l"`
			GsxA170R struct {
				T string `json:"$t"`
			} `json:"gsx$a170-r"`
			GsxA170Stop struct {
				T string `json:"$t"`
			} `json:"gsx$a170-stop"`
			GsxA170Time struct {
				T string `json:"$t"`
			} `json:"gsx$a170time"`
			GsxA180L struct {
				T string `json:"$t"`
			} `json:"gsx$a180-l"`
			GsxA180Stop struct {
				T string `json:"$t"`
			} `json:"gsx$a180-stop"`
			GsxA180Time struct {
				T string `json:"$t"`
			} `json:"gsx$a180time"`
			GsxA190L struct {
				T string `json:"$t"`
			} `json:"gsx$a190-l"`
			GsxA190D struct {
				T string `json:"$t"`
			} `json:"gsx$a190-d"`
			GsxA190Stop struct {
				T string `json:"$t"`
			} `json:"gsx$a190-stop"`
			GsxA190Time struct {
				T string `json:"$t"`
			} `json:"gsx$a190time"`
			GsxA200L struct {
				T string `json:"$t"`
			} `json:"gsx$a200-l"`
			GsxA200Stop struct {
				T string `json:"$t"`
			} `json:"gsx$a200-stop"`
			GsxA200Time struct {
				T string `json:"$t"`
			} `json:"gsx$a200time"`
			GsxA210L struct {
				T string `json:"$t"`
			} `json:"gsx$a210-l"`
			GsxA210Stop struct {
				T string `json:"$t"`
			} `json:"gsx$a210-stop"`
			GsxA210Time struct {
				T string `json:"$t"`
			} `json:"gsx$a210time"`
			GsxA220L struct {
				T string `json:"$t"`
			} `json:"gsx$a220-l"`
			GsxA220Stop struct {
				T string `json:"$t"`
			} `json:"gsx$a220-stop"`
			GsxA220Time struct {
				T string `json:"$t"`
			} `json:"gsx$a220time"`
		} `json:"entry"`
	} `json:"feed"`
}
